
trigger:
- main

pool:
  vmImage: ubuntu-latest

    
steps:
- task: AzureCLI@2
  displayName: 'Deploy DevCenter '
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription-WorkLoadIdentity'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo $(PLATFORM)
      az deployment sub create  --location westeurope  --template-file ./main.bicep --parameters main.bicepparam
    workingDirectory: 'Platform'
  env:
    PLATFORM: $PLATFORM
    MOIM_PAT: $MOIM_PAT