
trigger:
- main

pool:
  vmImage: ubuntu-latest

    
steps:
- task: AzureCLI@2
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription(c5b22afb-96db-4354-99a4-5f808d5221c6)'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: 'echo $(PLATFORM)'
    workingDirectory: 'infrastructure-templates'
  env:
    PLATFORM: $PLATFORM
    MOIM_PAT: $MOIM_PAT    