
trigger:
- main

pool:
  vmImage: ubuntu-latest

    
steps:
- task: AzureCLI@2
  displayName: 'Deploy Projects in DevCenter'
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription-WorkLoadIdentity'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo $(PLATFORM)      
      az deployment group create  --resource-group RGP-achilis  --template-file ./projects.bicep --parameters projects.bicepparam
    workingDirectory: 'Platform'
  env:
    PLATFORM: $(PLATFORM)